---
nginx_version: 1.28.0
nginx_checksum: sha256:c6b5c6b086c0df9d3ca3ff5e084c1d0ef909e6038279c71c1c3e985f576ff76a

njs_version: 0.9.3
njs_checksum: sha256:a1ad089a52ebd295489443faea3089d12df414f5da624446d6c2bf7d99ec36cb

modsecurity_version: 3.0.14
modsecurity_checksum: sha256:f7599057b35e67ab61764265daddf9ab03c35cee1e55527547afb073ce8f04e8

modsecurity_nginx_version: 1.0.4
modsecurity_nginx_checksum: sha256:6bdc7570911be884c1e43aaf85046137f9fde0cfa0dd4a55b853c81c45a13313

owasp_modsecurity_crs_version: 3.3.7
owasp_modsecurity_crs_checksum: sha256:e2e8ed9f72e802d5b54407f6ffd6930225955762f3ef297ee5ef8ec38305be89

quickjs_github_hash: 1fdc768
quickjs_checksum: sha256:941d6e6333b8803b7b7eeb1936aabac5f5cdad8fef1f06be6ced15a9f7b37639

tomcat_version: 11.0.11
tomcat_checksum: sha512:a26b2269530fd2fc834e9b1544962f6524cf87925de43b05ad050e66b5eaa76a4ad754a2c5fc4f851baf75a0ea1b0ed8f51082300393a4c35d8c2da0d7c535bd
tomcat_java_version: zulu21.44.17-ca-jre21.0.8
tomcat_java_checksum: sha256:0af24b31e3542ddd20e29f02c7dca46c1952db751843ae6b849534b257ecdd15
