---
nginx_version: 1.28.0
nginx_checksum: sha256:c6b5c6b086c0df9d3ca3ff5e084c1d0ef909e6038279c71c1c3e985f576ff76a

njs_version: 0.9.4
njs_checksum: sha256:7b3a9f14b0f09311d9031c2a252cb0e23c06baac2e586a7d12c75aa6cba4ca0e

modsecurity_version: 3.0.14
modsecurity_checksum: sha256:f7599057b35e67ab61764265daddf9ab03c35cee1e55527547afb073ce8f04e8

modsecurity_nginx_version: 1.0.4
modsecurity_nginx_checksum: sha256:6bdc7570911be884c1e43aaf85046137f9fde0cfa0dd4a55b853c81c45a13313

owasp_modsecurity_crs_version: 3.3.7
owasp_modsecurity_crs_checksum: sha256:e2e8ed9f72e802d5b54407f6ffd6930225955762f3ef297ee5ef8ec38305be89

quickjs_github_hash: b226856
quickjs_checksum: sha256:247005f18f6805a60f3d476a1f275c0f978841349ba3b6559fad7b5594bcaaaa

tomcat_version: 11.0.12
tomcat_checksum: sha512:85f8cfec9b1cdb9c7484b416c6e00cd7acb89c45e30090563b5d8f9c83c7e734bc9f5d32e110af129c5ea7d11f5632097c3e5230fe027e0219a9b0f52f42efac
tomcat_java_version: zulu21.44.17-ca-jre21.0.8
tomcat_java_checksum: sha256:0af24b31e3542ddd20e29f02c7dca46c1952db751843ae6b849534b257ecdd15
